spring:
  datasource:
    url: jdbc:h2:mem:hw10db
  sql:
    init:
      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 1000ms
      demoBreaker:
        maxAttempts: 4
        waitDuration: 2000ms
  circuitbreaker:
    instances:
      demoBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10 # размер окна сбора статистики ошибок
        minimumNumberOfCalls: 4 # минимальное количество запросов для активации circuit breaker
        failureRateThreshold: 50 # процент ошибок, при достижении которого срабатывает защита
        waitDurationInOpenState: PT1S # интервал ожидания восстановления сервиса - 1 сек


logging:
  level:
    ROOT: warn


management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: always