create table action_types
(
    id      bigserial,
    name    varchar(128),
    primary key (id)
);


create table devices (
                         id varchar(32),
                         full_name varchar(255),
                         latitude numeric(8,4),
                         longitude numeric(8,4),
                         primary key (id)
);

create table incidents (
                       id bigserial,
                       description varchar(255),
                       device_id varchar(32) references devices (id) on delete cascade,
                       primary key (id)
);

create table actions
(
    id      bigserial,
    whatdo    varchar(1024),
    incident_id bigint references incidents (id) on delete cascade,
    action_type_id bigint not null references action_types (id) on delete cascade,
    primary key (id)
);


create table users (
                       user_id bigserial  primary key,
                       username varchar(50) not null,
                       password varchar(100) not null

);

create table roles (
                       role_id bigserial,
                       role varchar(50) not null,
                       primary key (role_id)



);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id),
                            FOREIGN KEY (user_id) REFERENCES users(user_id),
                            FOREIGN KEY (role_id) REFERENCES roles(role_id)
);



CREATE TABLE IF NOT EXISTS acl_sid (
                                       id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                       principal tinyint NOT NULL,
                                       sid varchar(100) NOT NULL,
                                       PRIMARY KEY (id),
                                       constraint unique_uk_1 UNIQUE(sid,principal)
);

CREATE TABLE IF NOT EXISTS acl_class (
                                         id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                         class varchar(255) NOT NULL,
                                         PRIMARY KEY (id),
                                         constraint unique_uk_2 UNIQUE(class)
);

CREATE TABLE IF NOT EXISTS acl_entry (
                                         id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                         acl_object_identity bigint NOT NULL,
                                         ace_order int NOT NULL,
                                         sid bigint NOT NULL,
                                         mask int NOT NULL,
                                         granting tinyint NOT NULL,
                                         audit_success tinyint NOT NULL,
                                         audit_failure tinyint NOT NULL,
                                         PRIMARY KEY (id),
                                         constraint unique_uk_4 UNIQUE(acl_object_identity,ace_order)
);

CREATE TABLE IF NOT EXISTS acl_object_identity (
                                                   id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                   object_id_class bigint NOT NULL,
                                                   object_id_identity bigint NOT NULL,
                                                   parent_object bigint DEFAULT NULL,
                                                   owner_sid bigint DEFAULT NULL,
                                                   entries_inheriting tinyint NOT NULL,
                                                   PRIMARY KEY (id),
                                                   constraint unique_uk_3 UNIQUE(object_id_class,object_id_identity)
);

ALTER TABLE acl_entry
    ADD FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id);

ALTER TABLE acl_entry
    ADD FOREIGN KEY (sid) REFERENCES acl_sid(id);

--
-- Constraints for table acl_object_identity
--
ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id);

ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (object_id_class) REFERENCES acl_class (id);

ALTER TABLE acl_object_identity
    ADD FOREIGN KEY (owner_sid) REFERENCES acl_sid (id);
