server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:db/migration/V1__initial_schema.sql

  jmx:
    enabled: true

  data:
    rest:
      basePath: /hal

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

  file:
    name: booksApp1.log
    path: ./

