server:
  port: 8080

spring:
  data:
    mongodb:
      port: 0 # when flapdoodle using
#      port: 21017
      host: localhost
      database: books

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local


logging:
  level:
    ROOT: INFO